docs: updates relative slowness of KMS v1 compared to KMS v2
ritazh/website pull request #2
Opened 2023-03-21 21:11 UTC by nilekhc

2023-03-21 21:12 UTC, nilekhc commented
@ritazh @enj @aramase Let me know if I am missing anything.

2023-03-21 21:37 UTC, ritazh commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +`kms v1` | Uses envelope encryption scheme: Data is encrypted by data encryption keys (DEKs) using AES-CBC with [PKCS#7](https://datatracker.ietf.org/doc/html/rfc2315) padding (prior to v1.25), using
I think the recommended choice should just be kms v2, not kms v1.

2023-03-21 21:39 UTC, ritazh commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +`kms v2` | Uses envelope encryption scheme: Data is encrypted by data encryption keys (DEKs) using AES-GCM, DEKs are encrypted by key encryption keys (KEKs) according to configuration in Key Manageme
Should we say beta since 1.27?

2023-03-21 21:42 UTC, nilekhc commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +`kms v1` | Uses envelope encryption scheme: Data is encrypted by data encryption keys (DEKs) using AES-CBC with [PKCS#7](https://datatracker.ietf.org/doc/html/rfc2315) padding (prior to v1.25), using
Should we remove v1 altogether? I thought this table lists all available providers.

2023-03-21 21:52 UTC, aramase commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +`kms v1` | Uses envelope encryption scheme: Data is encrypted by data encryption keys (DEKs) using AES-CBC with [PKCS#7](https://datatracker.ietf.org/doc/html/rfc2315) padding (prior to v1.25), using
I think `The recommended choice for using a third party tool for key management.` should only be for kms v2 but we should keep v1 in the list until it's supported.

2023-03-22 20:50 UTC, ritazh commented
LGTM

2023-03-22 20:56 UTC, aramase requested changes

2023-03-22 20:56 UTC, aramase commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +`kms v2` | Uses envelope encryption scheme: Data is encrypted by data encryption keys (DEKs) using AES-GCM, DEKs are encrypted by key encryption keys (KEKs) according to configuration in Key Manageme
```suggestion
`kms v2` | Uses envelope encryption scheme: Data is encrypted by data encryption keys (DEKs) using AES-GCM, DEKs are encrypted by key encryption keys (KEKs) according to configuration in Key Management Service (KMS) | Strongest | Fast | 32-bytes |  The recommended choice for using a third party tool for key management. Available in beta from `v1.27`. A new DEK is generated at startup and reused for encryption. The DEK is rotated when the KEK is rotated. [Configure the KMS V2 provider](/docs/tasks/administer-cluster/kms-provider#configuring-the-kms-provider-kms-v2).
```

2023-03-22 21:07 UTC, aramase approved these changes

2023-03-23 18:35 UTC, enj commented
LGTM

2023-03-23 21:35 UTC, ritazh approved these changes

2023-03-23 21:35 UTC, merged