docs: add caution for unsupported vm save and restore
ritazh/website pull request #3
Opened 2023-03-21 21:23 UTC by aramase

2023-03-22 18:51 UTC, ritazh commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +For KMS v1, a new DEK is generated for each encryption. However, for KMS v2, a new DEK is generated at startup and reused for encryption. The DEK is rotated when the KEK is rotated.
Do we need to add something about:

> If the plugin is not healthy, the last DEK will be used for
encryption for up to three minutes (there is no difference on the
behavior of reads which have always used the DEK cache). This will
reduce the impact of a short plugin outage while making it easy to
perform storage migration after a key ID change (i.e. simply wait
ten minutes after the key ID change before starting the migration).

2023-03-22 20:11 UTC, aramase commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +For KMS v1, a new DEK is generated for each encryption. However, for KMS v2, a new DEK is generated at startup and reused for encryption. The DEK is rotated when the KEK is rotated.
This is going to be part of Mo's PR!

2023-03-22 20:42 UTC, ritazh commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +For KMS v1, a new DEK is generated for each encryption. However, for KMS v2, a new DEK is generated at startup and reused for encryption. The DEK is rotated when the KEK is rotated.
@enj

2023-03-22 20:42 UTC, ritazh commented
LGTM

2023-03-23 18:36 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +For KMS v1, a new DEK is generated for each encryption. However, for KMS v2, a new DEK is generated at startup and reused for encryption. The DEK is rotated when the KEK is rotated.
I did cover this at a high level in my PR.

2023-03-23 18:44 UTC, enj requested changes

2023-03-23 18:44 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +This can compromise the security of the encryption, as an attacker who knows the plaintext for one message can use this information to derive the key used to encrypt the other message.
I would drop this part because there is a lot of nuance here - for example you do not need to know the plaintext - you can compare two ciphertexts with the same nonce to leak the plaintext (I forget the exact details for key recovery).

2023-03-23 18:44 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +The kube-apiserver uses AES-GCM with an atomic counter as nonce for encryption. The following issues could occur if the VM is saved and restored:
```suggestion
The API server uses AES-GCM with a 12 byte nonce (8 byte atomic counter and 4 bytes random data) for encryption. The following issues could occur if the VM is saved and restored:
```

2023-03-23 18:44 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +
```suggestion

Both of these cases are partially mitigated by the 4 byte random nonce.

```

2023-03-23 18:45 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +This can compromise the security of the encryption, as an attacker who knows the plaintext for one message can use this information to derive the key used to encrypt the other message.
Drop the

> This can compromise the security of the encryption, as an attacker who knows the plaintext for one message can use this information to derive the key used to encrypt the other message.

is what I was trying to highlight.

2023-03-23 18:45 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +This can compromise the security of the encryption, as an attacker who knows the plaintext for one message can use this information to derive the key used to encrypt the other message.
Maybe just say

> This can compromise the security of the encryption.

2023-03-23 21:53 UTC, enj commented
LGTM

2023-03-23 21:55 UTC, ritazh approved these changes

2023-03-23 21:55 UTC, merged